include_recipe 'yum-epel' if node['platform_family'] == 'rhel'

package 'torque'
package 'torque-mom'
package 'torque-server'
package 'torque-scheduler'
package 'torque-devel'
package 'torque-drmaa'
package 'torque-drmaa-devel'
package 'torque-pam'
