---
driver:
  name: vagrant
  provider: libvirt
  customize:
    volume_cache: "\'writeback\'"

provisioner:
  name: chef_solo

platforms:
  - name: fedora-21
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1

suites:
  - name: install
    run_list:
      - recipe[torque::setup]
      - recipe[torque::install]
  - name: client
    run_list:
      - recipe[torque::setup]
      - recipe[torque::client]
  - name: server
    run_list:
      - recipe[torque::setup]
      - recipe[torque::server]
  - name: c0
    run_list:
      - recipe[torque::setup]
      - recipe[torque::compute]
  - name: c1
    run_list:
      - recipe[torque::setup]
      - recipe[torque::compute]
  - name: aio
    run_list:
      - recipe[torque::setup]
      - recipe[torque::server]
      - recipe[torque::client]
      - recipe[torque::compute]
