---
driver:
  name: vagrant
  provider: libvirt

provisioner:
  name: chef_solo

platforms:
  - name: fedora-21
  - name: fedora-20
  - name: centos-5.11
  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: install
    run_list:
      - recipe[torque::install]
    attributes:
  - name: server
    run_list:
      - recipe[torque::server]
  - name: compute
    run_list:
      - recipe[torque::compute]
  - name: aio
    run_list:
      - recipe[torque::server]
      - recipe[torque::compute]
